"""Feishu integration enumerations."""

from enum import StrEnum


class FeishuErrorCode(StrEnum):
    NOT_CONFIGURED = "FEISHU_NOT_CONFIGURED"
    AUTH_FAILED = "FEISHU_AUTH_FAILED"
    REQUEST_FAILED = "FEISHU_REQUEST_FAILED"
    RATE_LIMITED = "FEISHU_RATE_LIMITED"
    TIMEOUT = "FEISHU_TIMEOUT"
    NETWORK_ERROR = "FEISHU_NETWORK_ERROR"
    INVALID_RESPONSE = "FEISHU_INVALID_RESPONSE"
    DUPLICATE_CASE_RECORDS = "FEISHU_DUPLICATE_CASE_RECORDS"
    BINDING_RECORD_MISMATCH = "FEISHU_BINDING_RECORD_MISMATCH"
    RECORD_NOT_FOUND = "FEISHU_RECORD_NOT_FOUND"
    MAPPING_FAILED = "FEISHU_MAPPING_FAILED"
    UNSUPPORTED_SERVICE_CASE_STATUS = "FEISHU_UNSUPPORTED_SERVICE_CASE_STATUS"
    EVENT_PARSE_FAILED = "FEISHU_EVENT_PARSE_FAILED"


class FeishuBindingSyncStatus(StrEnum):
    PENDING = "pending"
    SYNCED = "synced"
    FAILED = "failed"


class FeishuEventReceiptStatus(StrEnum):
    RECEIVED = "received"
    PROCESSED = "processed"
    IGNORED = "ignored"
    FAILED = "failed"
