"""add opportunity domain

Revision ID: 2ce2df5de109
Revises: 64f1187d398e
Create Date: 2026-09-11 23:05:10.010474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce2df5de109'
down_revision: Union[str, Sequence[str], None] = '64f1187d398e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('official_url', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('resource_value', sa.JSON(), nullable=True),
    sa.Column('required_materials', sa.JSON(), nullable=True),
    sa.Column('application_process', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_type'), ['type'], unique=False)

    op.create_table('opportunity_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=32), nullable=False),
    sa.Column('expected_value', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_requirements_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('opportunity_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_sources_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_sources_opportunity_id'))

    op.drop_table('opportunity_sources')
    with op.batch_alter_table('opportunity_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_requirements_opportunity_id'))

    op.drop_table('opportunity_requirements')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_type'))
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))

    op.drop_table('opportunities')
    # ### end Alembic commands ###
