"""add enterprise domain

Revision ID: 64f1187d398e
Revises: a45ab0669e80
Create Date: 2026-09-11 22:45:41.026251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f1187d398e'
down_revision: Union[str, Sequence[str], None] = 'a45ab0669e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_region', sa.String(length=255), nullable=True),
    sa.Column('established_at', sa.Date(), nullable=True),
    sa.Column('enterprise_type', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('product_stage', sa.String(length=64), nullable=False),
    sa.Column('business_stage', sa.String(length=64), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('revenue_stage', sa.String(length=64), nullable=False),
    sa.Column('funding_stage', sa.String(length=64), nullable=False),
    sa.Column('ip_count', sa.Integer(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('current_constraint', sa.Text(), nullable=True),
    sa.Column('recent_events', sa.JSON(), nullable=True),
    sa.Column('available_materials', sa.JSON(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_states_enterprise_id'), ['enterprise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_states_enterprise_id'))

    op.drop_table('enterprise_states')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
