"""add content ingestion

Revision ID: 708c0e5dcb84
Revises: 2ce2df5de109
Create Date: 2026-09-11 23:49:24.036036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708c0e5dcb84'
down_revision: Union[str, Sequence[str], None] = '2ce2df5de109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('resolved_url', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('raw_title', sa.String(length=512), nullable=True),
    sa.Column('raw_publisher', sa.String(length=255), nullable=True),
    sa.Column('raw_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('fetch_status', sa.String(length=64), nullable=False),
    sa.Column('extraction_status', sa.String(length=64), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['opportunity_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingested_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingested_contents_source_id'), ['source_id'], unique=False)

    with op.batch_alter_table('opportunity_sources', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_sources', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    with op.batch_alter_table('ingested_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingested_contents_source_id'))

    op.drop_table('ingested_contents')
    # ### end Alembic commands ###
